"use client";
import Image from "next/image";
import { Expand, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Reveal, SectionHeading } from "./ui";

export function Story() {
 const [open, setOpen] = useState(false);
 const closeButton = useRef<HTMLButtonElement>(null);
 useEffect(() => { if (!open) return; const previousFocus = document.activeElement as HTMLElement | null; const handleKey = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(false); if (e.key === "Tab") { e.preventDefault(); closeButton.current?.focus(); } }; document.body.style.overflow = "hidden"; closeButton.current?.focus(); addEventListener("keydown", handleKey); return () => { document.body.style.overflow = ""; removeEventListener("keydown", handleKey); previousFocus?.focus(); }; }, [open]);
 return <section id="story" className="section story"><div className="shell story-grid"><Reveal className="story-image"><button onClick={() => setOpen(true)} aria-label="Open the RUBIE story screenshot in a larger view"><Image src="/rubie-story.jpeg" alt="Public X conversation between Frank Chaparro and Jeremy Allaire that inspired RUBIE" fill quality={90} sizes="(max-width: 768px) calc(100vw - 28px), (max-width: 1200px) 52vw, 620px"/><span><Expand size={17}/> Expand image</span></button></Reveal><Reveal className="story-copy"><SectionHeading eyebrow="THE ORIGIN" title="The Story of RUBIE"/><div className="prose"><p>Every great meme starts with a story.</p><p>RUBIE was inspired by one unforgettable exchange between Jeremy Allaire and his friend Frank Chaparro.</p><p>After a lunch together, Frank joked that his payment failed. Jeremy fired back with a legendary reply, recalling that Frank’s excuse was:</p><blockquote>“My dog ate my credit card.”</blockquote><p>That single sentence became the heart of the meme.</p><p>Behind that excuse was Rubie, Frank’s dog.</p><p>What started as a funny moment between friends became an inside joke that the crypto community could rally around.</p><p>It’s celebrating one of the internet’s most memorable ‘dog ate my credit card’ moments—bringing humor, community, and memes to the ARC ecosystem.</p></div><p className="note">RUBIE is an independent community meme coin inspired by this public exchange.</p></Reveal></div>{open && <div className="lightbox" role="dialog" aria-modal="true" aria-label="Story image preview" onClick={() => setOpen(false)}><button ref={closeButton} aria-label="Close image"><X/></button><div onClick={e => e.stopPropagation()}><Image src="/rubie-story.jpeg" alt="Public X conversation between Frank Chaparro and Jeremy Allaire that inspired RUBIE" fill quality={95} sizes="95vw"/></div></div>}</section>;
}
